"""Initial migration

Revision ID: 4b2ca3516cc2
Revises: 
Create Date: 2025-06-30 21:10:54.875407

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4b2ca3516cc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('author', sa.String(), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('genre', sa.String(), nullable=False),
                    sa.Column('pages', sa.Integer(), nullable=False),
                    sa.Column('available', sa.Boolean(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('cover_url', sa.String(), nullable=True),
                    sa.Column('rating', sa.Float(), nullable=True),
                    sa.Column('isbn', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
